version: '3.8'

services:
  spring:
    build: ./backend
    image: your-dockerhub-username/spring-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - chatting

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: your-dockerhub-username/react-frontend:latest
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - spring
    networks:
      - chatting

  nginx:
    build:
      context: ./frontend
    image: your-dockerhub-username/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring
      - react
    networks:
      - chatting

networks:
  chatting:
    driver: bridge