name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          sudo apt-get install -y docker-compose

      - name: Build and push Docker image using docker-compose
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key for remote server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to remote server
        run: |
          ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null user@${{ secrets.SERVER_IP }} <<EOF
            if ! command -v docker-compose &> /dev/null
            then
              echo "docker-compose not found, installing..."
              sudo apt-get install -y docker-compose
            fi
            cd /home/ubuntu/toy-chatting
            docker-compose -f docker-compose.prod.yml pull  # 최신 이미지를 풀
            docker-compose -f docker-compose.prod.yml up -d  # 서비스 재시작
          EOF